services:  
    web:  
        build: .  
        container_name: todoList
        restart: always  
        depends_on:  
            - mysql  
        ports:  
            - "8080:80"  #docker内で使ってる番号と被らないように(8080部分)。被る場合はdockerで被ってる番号をstopする,それかこの番号を変える
        volumes:  
            - .:/var/www/html  
        # environment:  
        #     - SUPER_ENVIRONEMENT_VARIABLE=Mon Super Site
    mysql:  
        image: mariadb  
        container_name: to_do_list
        restart: always  
        environment:  
            - MARIADB_ROOT_PASSWORD=root  
        ports:  
            - "3308:3306"  
        # volumes:  
        #     - ./mysql.sql:/docker-entrypoint-initdb.d/mysql.sql

    phpmyadmin:  
        image: phpmyadmin  
        container_name: todoListAdmin 
        restart: always  
        depends_on:  
            - mysql  
        environment:  
            PMA_ARBITRARY: 1  
            PMA_HOST: mysql  
        ports:  
            - "8081:80"