services:  
    web:  
        build: .  
        container_name: todoListMVC
        restart: always  
        depends_on:  
            - mysql  
        ports:  
            - "8080:80"  #docker内で使ってる番号と被らないように(8080部分)。被る場合はdockerで被ってる番号をstopする,それかこの番号を変える
        volumes:  
            - ./app:/var/www/html  
        environment:  
            - TZ=Europe/Paris
            - DB_PASSWORD=${DB_PASSWORD}
            - DB_USER=${DB_USER}
            - DB_NAME=${DB_NAME}
            - DB_HOST=mysql
            
    mysql:  
        image: mariadb
        container_name: to_do_listMVC
        restart: always  
        environment:  
            - MARIADB_ROOT_PASSWORD=${DB_PASSWORD}
            - TZ=Europe/Paris
        ports:  
            - "3308:3306"  
        volumes:  
            - data:/var/lib/mysql # Conserve les données de la base (persistantes même si le conteneur est supprimé DBデータを永続化,コンテナを削除しても残る)
        #     - ./mysql.sql:/docker-entrypoint-initdb.d/mysql.sql

    phpmyadmin:  
        image: phpmyadmin  
        container_name: todoListAdminMVC
        restart: always  
        depends_on:  
            - mysql  
        environment:  
            PMA_ARBITRARY: 1  
            PMA_HOST: mysql  
        ports:  
            - "8081:80"
volumes:
    data: null